tasks:
  - init: pip3 install -r ./requirements.txt
  - init: pip3 install -U pytest --user
  - init: pip3 install -U pylint --user
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
