tasks:
  - init: /bin/python3 -m pip install -U pytest mock pylint awscli black flake8 -r ./requirements.txt --user
  - init: pyenv shell 2.7.17 && pip install -U pytest mock pylint awscli -r ./requirements.txt --user
  - init: [[ -d /workspace/.aws ]] && ln -sf /workspace/.aws ~/.aws
  - init: [[ -f /workspace/.hpecp_service ]] && ln -sf /workspace/.hpecp_service ~/.hpecp_service
  - command: cd docs && make html && cd build/html && python3 -m http.server 8080
    name: Static Server
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
