tasks:
  - init: /usr/bin/python3 -m pip install -U pytest mock pylint -r ./requirements.txt --user
  - init: pyenv shell 2.7.17 && pip install -U pytest mock pylint -r ./requirements.txt --user
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
