tasks:
  - init: pip3 install -r ./requirements.txt
  - init: pip3 install -U pytest --user
  - init: pip3 install -U pylint --user
  - init: pyenv install 3.6.10
  - init: pyenv install 3.5.9
  - init: pyenv install 3.7.7
  - init: pyenv install 3.8.2
  - init: pyenv install 3.9-dev
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
