tasks:
  - command: cd docs && make html && cd build/html && python3 -m http.server 8080
    name: Static Server
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
