tasks:
  - command: /home/gitpod/.pyenv/versions/2.7.17/bin/python2 -m pip install -U pytest mock awscli -r ./requirements.txt --user && exit
  - command: /home/gitpod/.pyenv/versions/3.5.9/bin/python3 -m pip install -U pytest tox mock awscli flake8 -r ./requirements.txt --user && exit
  - command: /home/gitpod/.pyenv/versions/3.6.9/bin/python3 -m pip install -U pytest tox mock awscli black flake8 -r ./requirements.txt --user && exit
  - command: /home/gitpod/.pyenv/versions/3.7.7/bin/python3 -m pip install -U pytest tox mock awscli black flake8 -r ./requirements.txt --user && exit
  - command: /home/gitpod/.pyenv/versions/3.8.2/bin/python3 -m pip install -U pytest tox mock awscli black flake8 -r ./requirements.txt --user && exit
  - command: /home/gitpod/.pyenv/versions/3.9-dev/bin/python3 -m pip install -U pytest tox mock awscli black flake8 -r ./requirements.txt --user && exit
  - command: cd docs && make html && cd build/html && python3 -m http.server 8080
  - command: echo "Welcome"
    name: Static Server
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
