language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: 
  - pip install tox-travis
  - pip install python-coveralls
  - pip install coverage==4.5.4
  - pip install sphinx

script:
  - tox
  - coverage run --source hpecp setup.py test
  - coverage report -m
  - cd docs
  - make html

after_success:
  - coveralls

