language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install: 
  - pip install tox-travis
  - pip install python-coveralls
  - pip install coverage==4.5.4

script:
  - tox
  - coverage run --source hpecp setup.py test
  - coverage report -m

after_success:
  - coveralls

