language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: 
  - pip install tox-travis
  - pip install python-coveralls
  - pip install coverage==4.5.4

script:
  - tox
  - coverage run --source hpecp setup.py test
  - coverage report -m
  - python --version 2>&1 | grep '2.7' || python setup.py install # (don't run on 2.7)
  - python --version 2>&1 | grep '2.7' || echo q | ./bin/hpecp --help # check cli outputs help and doesn't return an error (don't run on 2.7)

after_success:
  - coveralls

jobs:
  include:
    - stage: deploy
      python: 3.8
      install: 
        - pip install tox-travis
        - pip install python-coveralls
        - pip install coverage==4.5.4
        - pip install tabulate
        - pip install six
        - pip install polling
        - pip install sphinx
      script:
        - cd docs
        - make html
        - touch ./build/html/.nojekyll
      deploy:
         provider: pages
         skip_cleanup: true
         github_token:
           secure: h+fqasd4ZOdm0IxVRQVl3IKmENIB3AB5IeVSNK7J35LMG+/QzaZD26naD0CVfa7RbGeKv9EpV91f3SHR/SikY0l+IA2OT0607SWdDYxFYrbrPzEwG8N72UwwcCCO2hfscE68krRYt2zDoWY7chZeJsAHTcL0l5ap2k34AYiDnBUW1PffgAGoVLbBH1dcTRi3pYCx0rbsQYv06D3wkuGF/Yin04uuxFaE+aLIfKxJVAeeiKcsPEzVyZHDOI08r6lzRjtjT+p1HOgnPH08pLcHdpRC0lP9RK/xCPvbhj5zS0PnDqcbYjpWpLK1Jg8MzLaHTo3223ygMmiNLXZptb6anfuulLBpzYLetgLF4QZsQYQfkY/IdtGVR2oWtq+0v54qFeSOH88SQPqOtyKTj0WlBT343y+DoVbhLNKvSmxiWFE/fr2b7VXYqF/gllZHZdQ2WQfI1F/lHeWZtScZaRK5sq7ofyecCpNy+Hw55F2i1Q+YTdJD8VtD/Zmz3j+OTW6uMUKPxnBrHnK6hjrrTg/t+mVhP7Ui4voEuiv5SSdTwGd4iYLdFpOchmduGW0mRzAeES+TOExpWmLnYKkKgQ1XiZ4rX6woZNIVAk0wTHzl2DpYaCpDHYwhNlzIyLD0j4gmwdlE4JD5Ut1YLr+gnMcoLMxPLY96vMohRI0WML+38O0=
         keep-history: true
         on:
           branch: master
         local_dir: docs/build/html
