language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: 
  - pip install tox-travis
  - pip install python-coveralls
  - pip install coverage==4.5.4

script:
  - tox
  - coverage run --source hpecp setup.py test
  - coverage report -m

after_success:
  - coveralls

jobs:
  include:
    - stage: deploy
      python: 3.8
      install: 
        - pip install tox-travis
        - pip install python-coveralls
        - pip install coverage==4.5.4
        - pip install sphinx
      script:
        - tox
        - cd docs
        - make html
        - touch ./build/html/.nojekyll
      deploy:
         provider: pages
         skip_cleanup: true
         github_token: $GITHUB_TOKEN
         keep-history: true
         on:
           branch: master
         local_dir: docs/build/html
