on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: hpecp-python-library (Build & Test)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Checkout ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          tox -e py
          coverage run --source hpecp,bin setup.py test
          coverage report -m
          python setup.py install
      - name: Coverage report (Coveralls)
        run: |
          COVERALLS_REPO_TOKEN=g0waCcM28o3gLyuF0JbAmWRbYl1iS9lyp coveralls
