name: hpecp-python-library Build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: hpecp-python-library (Build & Test)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
      - name: Checkout ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install tox
          pip install python-coveralls
      - name: Run tests
        run: |
          tox
          coverage run --source hpecp,bin setup.py test
          coverage report -m
          python --version 2>&1 | grep '2.7' || python setup.py install
          python --version 2>&1 | grep '2.7' || echo q | ./bin/hpecp --help
      - name: Coverage report
        run: |
          coveralls
