name: Deploy

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_TOKEN }}
    - uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install and Run Python 2.7
      run: |
        sudo apt-get install python-setuptools
        pip install hpecp
        hpecp version
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and Run Python 3.x
      run: |
        sudo apt-get install python3-setuptools
        pip3 install hpecp
        hpecp version
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install tabulate
          pip install sphinx
          pip install six
          pip install polling
      - name: Build Docs
        run: |
          pip install -r requirements.txt
          cd docs
          make html
          touch ./build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.5
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
